# Generated by Django 3.2.6 on 2021-08-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='stauts',
            field=models.CharField(blank=True, choices=[('availible', 'availible'), ('rented', 'rented'), ('sold', 'sold')], max_length=50, null=True),
        ),
    ]
